name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt        
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: 'win64_msvc2019_64'
          dir: '${{github.workspace}}/'

      - name: Build
        shell: bash
        env:
          CXX: cl.exe
        run: |
          cd bin
          cmake ..
          cmake --build . --parallel $(nproc) --config Release
          cd $GITHUB_WORKSPACE/bin/Release
          $GITHUB_WORKSPACE/Qt/5.15.2/msvc2019_64/bin/windeployqt.exe --release Fast-Discord.exe
          cp $GITHUB_WORKSPACE/libs/64/bin/libsodium.dll .
          cp $GITHUB_WORKSPACE/libs/64/bin/opus.dll .
          cp $GITHUB_WORKSPACE/libs/64/bin/libcrypto-1_1-x64.dll .
          cp $GITHUB_WORKSPACE/libs/64/bin/libssl-1_1-x64.dll .
          cp -r ../res .

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: "Fast-Discord - Windows x64"
          path: '${{github.workspace}}/bin/Release'
