name: Build Macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt        
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          arch: x64
          dir: '${{github.workspace}}/'
      
      - name: Install opus and sodium
        run: brew install libsodium opus

      - name: Build
        shell: bash
        run: |
          cd bin
          cmake ..
          cmake --build . --parallel $(nproc)
          mkdir build
          mv Fast-Discord build

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: "Fast-Discord - MacOs x64"
          path: '${{github.workspace}}/bin/build'
